### PR TITLE
feat: add lockfile check workflow for node v20

### PR DESCRIPTION
**Pull request by BilalQamar95**
### Description 

This PR introduces a new GitHub Actions workflow named `lockfile check for Node v20` which performs following checks 
- **Node.js Version Check:** Reads the `.nvmrc` file to ensure it specifies node`v20`, and verifies that the current node version matches this requirement.
- **NPM Version Check:** Verifies the use of NPM `v10` and ensures the lockfile version in `package-lock.json` is 3.
- **Dependency Synchronization Check:** Detects mismatches between `package.json` and `package-lock.json`, prompting for regeneration if needed.

### CODE REVIEW

**Review by UsamaSadiq — APPROVED** [review]
Looks good to be merged.

**Comment by BilalQamar95** [comment]
@feanil Can you please review and merge (since I don't have the required permissions for it) PR. Thank you

**Comment by feanil** [comment]
We still have 2 older versions of this workflow, can we delete either of them as a part of this addition?

**Comment by BilalQamar95** [comment]
> We still have 2 older versions of this workflow, can we delete either of them as a part of this addition?

@feanil `lockfileversion-check` is still being used for [studio-frontend](https://github.com/openedx/studio-frontend/blob/8506636673b0dab1b66a223c0c9a0184d67ca5f1/.github/workflows/lockfileversion-check.yml#L13) which is still on `node v16` & `lockfileversion-check-v3` is being used for multiple MFEs in both [edx](https://github.com/search?q=org%3Aedx+lockfileversion-check-v3.yml&type=code) and [openedx](https://github.com/search?q=org%3Aopenedx+lockfileversion-check-v3.yml&type=code) org. [lockfileversion-check-v3](https://github.com/openedx/.github/blob/master/.github/workflows/lockfileversion-check-v3.yml) seems to be a redundant workflow and should be replaced with [lockfile-check](https://github.com/openedx/.github/blob/master/.github/workflows/lockfile-check.yml) across all MFEs, we can deprecate `lockfileversion-check-v3` afterwards, we can create a separate ticket for this

**Review by feanil — APPROVED** [review]
Makes sense thanks @BilalQamar95 and thanks for ticketing and taking on the cleanup.  Please link those tickets here once you have them.

**Pull request merged**
